{
 "title": "Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "master0.fledge2.ilabt-imec-be.wall1.ilabt.iminds.be,worker0.fledge2.ilabt-imec-be.wall1.ilabt.iminds.be"
   }
  ]
 },
 "panels": [
  {
   "title": "System Specification",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores",
     "type": "stat",
     "description": "Number of CPU Cores",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\",hostname=\"$hostname\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "stat",
     "description": "Available memory",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{hostname=\"$hostname\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "System Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(cpu) (100 * irate(node_cpu_seconds_total{hostname=\"$hostname\",mode!=\"idle\"}[$__interval]))",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(100 * irate(node_cpu_seconds_total{hostname=\"$hostname\",mode!=\"idle\"}[$__interval]))",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{hostname=\"$hostname\"} - node_memory_MemAvailable_bytes{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{hostname=\"$hostname\"}[$__interval]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{hostname=\"$hostname\"}[$__interval]))",
     "legendFormat": "Write"
    }
   ]
  },
  { "title": "Process Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (groupname) (100 * irate(namedprocess_namegroup_cpu_seconds_total{hostname=\"$hostname\",mode!=\"idle\"}[$__interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "CPU Usage (System)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * irate(namedprocess_namegroup_cpu_seconds_total{hostname=\"$hostname\",mode=\"system\"}[$__interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "CPU Usage (User)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * irate(namedprocess_namegroup_cpu_seconds_total{hostname=\"$hostname\",mode=\"user\"}[$__interval])",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Resident)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{hostname=\"$hostname\",memtype=\"resident\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Memory Usage (Virtual)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes{hostname=\"$hostname\",memtype=\"virtual\"}",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Disk Usage (Read)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(irate(namedprocess_namegroup_read_bytes_total{hostname=\"$hostname\"}[$__interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Disk Usage (Write)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(rate(namedprocess_namegroup_write_bytes_total{hostname=\"$hostname\"}[$__interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  { "title": "Feather Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(feather_process_cpu_seconds_total{hostname=\"$hostname\"}[$__interval]) * 100",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "Memory Usage (Resident)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "feather_process_resident_memory_bytes{hostname=\"$hostname\"}",
     "legendFormat": "Resident"
    }
   ]
  },
  {
   "title": "Memory Usage (Virtual)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "feather_process_virtual_memory_bytes{hostname=\"$hostname\"}",
     "legendFormat": "Virtual"
    }
   ]
  },
  {
   "title": "Memory Statistics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "feather_go_memstats_sys_bytes{hostname=\"$hostname\"}",
     "legendFormat": "System"
    },
    {
     "expr": "feather_go_memstats_alloc_bytes{hostname=\"$hostname\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "feather_go_memstats_stack_sys_bytes{hostname=\"$hostname\"}",
     "legendFormat": "System (stack)"
    },
    {
     "expr": "feather_go_memstats_heap_sys_bytes{hostname=\"$hostname\"}",
     "legendFormat": "System (heap)"
    },
    {
     "expr": "feather_go_memstats_mspan_sys_bytes{hostname=\"$hostname\"}",
     "legendFormat": "System (mspan)"
    },
    {
     "expr": "feather_go_memstats_buck_hash_sys_bytes{hostname=\"$hostname\"}",
     "legendFormat": "System (buck_hash)"
    },
    {
     "expr": "feather_go_memstats_gc_sys_bytes{hostname=\"$hostname\"}",
     "legendFormat": "System (gc)"
    },
    {
     "expr": "feather_go_memstats_other_sys_bytes{hostname=\"$hostname\"}",
     "legendFormat": "System (other)"
    }
   ]
  },
  {
   "title": "Garbage Collector Statistics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "feather_go_memstats_heap_alloc_bytes{hostname=\"$hostname\"}",
     "legendFormat": "Live Heap"
    },
    {
     "expr": "feather_go_memstats_next_gc_bytes{hostname=\"$hostname\"}",
     "legendFormat": "New Heap"
    }
   ]
  },
  {
   "title": "Golang Statistics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "feather_go_goroutines{hostname=\"$hostname\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  { "title": "Minecraft Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "mc_jvm_threads_current", "legendFormat": "current" }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mc_jvm_memory{hostname=\"$hostname\", type=~\"allocated|max\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "mc_jvm_memory{hostname=\"$hostname\", type=\"allocated\"} - on () mc_jvm_memory{hostname=\"$hostname\", type=\"free\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "JVM GC Load",
   "type": "timeseries",
   "description": "Percentage of time spent collecting garbage.",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(mc_jvm_gc_collection_seconds_sum{hostname=\"$hostname\"}[$__interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Ticks per Second",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "mc_tps{hostname=\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chunks Loaded",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mc_loaded_chunks_total{hostname=\"$hostname\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Players Online",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 4, "x": 16, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mc_players_online_total{hostname=\"$hostname\"}",
     "legendFormat": "{{world}}"
    },
    {
     "expr": "sum(mc_players_online_total{hostname=\"$hostname\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "World Size",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mc_world_size{hostname=\"$hostname\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Number of Entities",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "sum by(type) (mc_entities_total{hostname=\"$hostname\"})",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum (mc_entities_total{hostname=\"$hostname\"})",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Number of Chickens",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 107 },
   "targets": [
    {
     "expr": "mc_entities_total{hostname=\"$hostname\", type=\"CHICKEN\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Villagers",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 107 },
   "targets": [
    {
     "expr": "mc_entities_total{hostname=\"$hostname\", type=\"VILLAGER\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}